Hard code getQuizQuestion
JuliaSull/SPSTravelApp pull request #7
Opened 2021-04-01 14:00 UTC by AlexanderRoper

2021-04-01 14:02 UTC, AlexanderRoper commented
Will work with Manuela on Friday to get Datastore implemented

2021-04-01 19:53 UTC, JuliaSull requested changes

2021-04-01 19:53 UTC, JuliaSull commented on src/main/java/com/google/sps/servlets/QuizQuestionsServlet.java
> +            quiz.put("Which of these would you most like to do?", List.of("Go on a hike in nature", "Take a trip downtown", "Go to a museum", "Take a day for relaxation"));
Make sure to run this through https://beautifier.io/

2021-04-01 19:53 UTC, JuliaSull commented on src/main/java/com/google/sps/servlets/QuizQuestionsServlet.java
> +        a.add("Relax");
This can be deleted since it's never used.

2021-04-01 19:53 UTC, JuliaSull commented on src/main/java/com/google/sps/servlets/QuizQuestionsServlet.java
> +        return json;
`return new Gson().toJson(quest);`

2021-04-01 19:53 UTC, JuliaSull commented on src/main/java/com/google/sps/servlets/QuizQuestionsServlet.java
> +    * Converts a ServerStats instance into a JSON string using the Gson library.
nit: Converts a QuizQuestion instance ...

2021-04-01 19:53 UTC, JuliaSull commented on src/main/java/com/google/sps/servlets/QuizQuestionsServlet.java
> +        // Convert the server stats to JSON
nit: quiz question to JSON

2021-04-01 19:53 UTC, JuliaSull commented on src/main/java/com/google/sps/servlets/QuizQuestionsServlet.java
> +  static final long serialVersionUID = 0;
It doesn't look like this is used anywhere else.

2021-04-01 19:53 UTC, JuliaSull commented on src/main/java/com/google/sps/servlets/QuizQuestionsServlet.java
> +/** Handles requests sent to the /hello URL. Try running a server and navigating to /hello! */
nit: update this comment.

2021-04-02 20:31 UTC, JuliaSull approved these changes

2021-04-04 22:34 UTC, merged